"""Phase 2 of the audit pipeline: bind one audit to its database(s) → `mapping.json`.

Emits the structured **`mapping.json`** (storage-layout §2; mapping-artifact-redesign.md
§3.3): the single source of truth for *where every audit concept lives* and *how each
value is obtained*. Takes the audit specification (`spec.json`, A1.1) and the schema
model (`model.json`, A1.1) of every database the audit draws from, and makes one LLM
call to produce — for every audit field — its source `database -> table.column`, the
**`kind`** (`direct` / `interpret`, decided HERE because only now is the database
known), and an optional per-field **`code`** (a `code -> meaning` map operationalising
the audit field's permitted values against this database). It also resolves the
cohort `identity` (anchor + join keys) and carries the workbook `regions` forward as
DATA (cell refs / ranges are never LLM-retyped — they flow through from the inputs).

Ownership (the file is SHARED with A6.1): this builder owns `schema_version`,
`audit`, `databases`, `description`, `identity`, `regions`, and `fields[]`. The
`criteria_bindings` + `not_expressible` blocks are owned by **A6.1** in the same
file; this builder writes `criteria_bindings: []` as a schema-valid skeleton for
A6.1 to populate. The model is validated against the S0 schema
(`mapping.schema.json`) before it is returned, so a malformed document is never
persisted.

`mapping.json` is PURELY REGENERABLE — it carries no user-set state (defaults live
in `spec.json`, §6). This phase runs lazily at run-start, because the mapping
depends on the *pair* (audit, database) which only exists when a user picks both.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from core.clients import llm
from core.clients.llm_builder import BuilderValidationError, build_validated
from core.config import DATABASES_DIR, TEMPLATES_DIR
from core.contracts import validate_against_schema
from core.mapping.build_criteria import build_criteria_bindings
from core.mapping.build_populate_spec import BuildError, fold_executable
from pydantic import BaseModel, ConfigDict, Field

logger = logging.getLogger(__name__)

_SCHEMA_FILE = "mapping.schema.json"
_VALID_KINDS = {"direct", "interpret"}


class _MappingLLMOutput(BaseModel):
    """Typed contract for Phase-2 mapping output generated by the LLM."""

    model_config = ConfigDict(extra="ignore")

    description: Any = None
    database_summaries: Any = None
    identity: Any = None
    regions: Any = Field(default_factory=list)
    fields: Any = Field(default_factory=list)


_PROMPT = """\
You bind one clinical audit to the database(s) it draws from, producing the
MAPPING — the single source of truth for WHERE every audit field's value lives and
HOW it is obtained. You are given the audit specification (its fields, with cell,
name, type, and permitted values) and, for EACH source database, its schema model
(tables, columns, types, and — for filterable columns — their value sets / codes).

Produce ONLY a single JSON object — no preamble, no markdown fences, no commentary.

Output shape (only these keys — do NOT emit schema_version, audit, databases, or
criteria_bindings; those are added by the caller):

{
  "description": "<one paragraph: which database/table holds the primary entity and where each major group of fields comes from>",
  "database_summaries": {
    "<db slug>": "<ONE sentence: what THIS audit draws from THIS database, e.g. 'Patient demographics and registration details joined per visit.'>"
  },
  "identity": {
    "anchor": "<db> -> <table>.<column>",
    "grain": "<prose, e.g. 'one patient per birth record'>",
    "keys": ["<db> -> <table>.<column>", ...],
    "patient_grain_rule": "<how a criterion is applied without inflating the count, e.g. EXISTS/IN over the anchor>"
  },
  "regions": [
    { "id": "<region id, e.g. ALL>", "sheet": "<sheet name>", "kind": "row_per_entity",
      "data_range": "<A1 range, e.g. A2:AQ500>",
      "row_id": { "cell": "<column letter, e.g. A>", "header": "<header text>" } }
  ],
  "fields": [
    { "region": "<region id>", "cell": "<column letter>", "header": "<header text>",
      "kind": "direct | interpret",
      "sources": ["<db> -> <table>.<column>", ...],
      "how_to_combine": "<optional prose; primarily for interpret fields>",
      "code": { "<code>": "<meaning>" } }
  ]
}

Rules:
- `database_summaries` carries one entry PER database you were given (key = the db
  slug, exactly as given): a single TEMPLATE-SPECIFIC sentence saying what this
  audit draws from that database — name the role its bound tables play for THIS
  audit, not a generic description of the database.
- Map EVERY audit field into its region, keeping the SAME `cell` letter and `header`
  text. Do not add, drop, rename, or reorder fields.
- Carry each region's `sheet`, `data_range`, and `row_id` THROUGH from the audit —
  copy them verbatim; never invent or recompute a cell ref or range.
- `kind` is decided HERE: `direct` = a confident straight COPY of a structured column
  (optionally code-translated via `code`) — the value sits in the column as-is, one
  column → one cell. `interpret` = the value must be DERIVED from evidence, because no
  structured column holds it cleanly. Default to `direct` ONLY when a structured column
  holds the value plainly.
  CRITICAL: a free-text / note column (e.g. `clinical_notes.text`, a comment or summary
  field) is NOT a structured column. If the value lives in free text — where only a
  particular word, number, or sentence is the answer, not the whole passage — the field
  MUST be `interpret`. Marking it `direct` would copy the ENTIRE note into the cell.
  Likewise, anything needing MORE than one column (a value combined across columns/DBs,
  or chosen among many rows for one patient) is `interpret`, never `direct`.
  (If a `direct` column merely needs a code the `code` map misses, leave it `direct` —
  the run escalates that one cell at run time; do not over-classify to `interpret`.)
- `sources` is a list of `<db> -> <table>.<column>`; every db slug MUST be one you
  were given, and every table/column MUST appear verbatim (exact casing) in that
  database's schema model. Never invent or misattribute a column. For interpret
  fields, `sources` are the evidence columns to read.
- `code` (OPTIONAL, on ANY field) is the `code -> meaning` map the cell's value MUST
  use — it operationalises the audit field's permitted values against THIS database.
  Add it when the audit field is coded/categorical and the database stores a
  different encoding: for a `direct` field the executor maps the source value onto
  the matching code; for an `interpret` field the agent must output one of the codes.
  Omit it when the value is filled as-is.
- `identity.anchor` defines one cohort member; every criterion is evaluated relative
  to it. `keys` lists the join keys tying records back to the anchor (at least the
  anchor key). When a database lists MEASURED identity links, copy the linked
  columns into `keys` exactly as given — they are profiled facts; never substitute
  a name-based guess, and never link two databases that have no measured link.
- Output only the JSON object, starting with `{`.
"""


# --- clean rendered views of the JSON inputs (governing principle §2) ----------


def _render_audit_spec(audit: dict[str, Any]) -> str:
    """Render `spec.json` to a clean view for the prompt — never raw braces."""
    lines = [
        f"Audit: {audit.get('title') or audit.get('audit')}",
        f"Grain: {audit.get('grain', '')}",
        f"Description: {audit.get('description', '')}",
        "",
        "Fields:",
    ]
    for f in audit.get("fields", []) or []:
        bits = [
            f"  - cell {f.get('cell', '?')} — {f.get('name', '')} ({f.get('type', '')})"
        ]
        pv = f.get("permitted_values")
        if isinstance(pv, dict) and pv:
            bits.append("permitted: " + ", ".join(f"{k}={v}" for k, v in pv.items()))
        if f.get("unit"):
            bits.append(f"unit: {f['unit']}")
        if f.get("notes"):
            bits.append(f"notes: {f['notes']}")
        lines.append(". ".join(bits))
    return "\n".join(lines)


def _render_column(col: dict[str, Any]) -> str:
    bits = [f"      - {col.get('name', '?')} ({col.get('type', '')})"]
    if col.get("description"):
        bits.append(col["description"])
    if col.get("values"):
        bits.append("values: " + ", ".join(str(v) for v in col["values"]))
    if col.get("range"):
        bits.append(f"range: {col['range']}")
    codes = col.get("codes")
    if isinstance(codes, dict) and codes:
        bits.append("codes: " + ", ".join(f"{k}={v}" for k, v in codes.items()))
    return ". ".join(bits)


def _render_database_model(db: dict[str, Any]) -> str:
    lines = [
        f"=== DATABASE: {db.get('database')} ({db.get('title', '')}) ===",
        f"Description: {db.get('description', '')}",
    ]
    links = db.get("identity_links") or []
    if links:
        lines.append(
            "Measured identity links (FACTS — value-overlap profiled at indexing; "
            "identity.keys MUST follow these, never a name-based guess):"
        )
        for link in links:
            lines.append(
                f"  {db.get('database')} -> {link.get('column')}"
                f"  =  {link.get('target')}  ({link.get('evidence')})"
            )
    fks = db.get("foreign_keys") or []
    if fks:
        lines.append(
            "Within-database foreign keys (FACTS — value-overlap profiled at "
            "indexing; use these to author join_path and to reach columns in "
            "non-anchor tables, never a name-based guess):"
        )
        for fk in fks:
            trust = "declared" if fk.get("declared") else fk.get("evidence")
            lines.append(
                f"  {fk.get('column')} -> {fk.get('target')}"
                f"  [{fk.get('cardinality')}]  ({trust})"
            )
    notes = ((db.get("conventions") or {}).get("notes")) or []
    if notes:
        lines.append("Database-wide conventions (orientation):")
        for note in notes:
            lines.append(f"  - {note}")
    lines.append("Tables:")
    for t in db.get("tables", []) or []:
        grain = t.get("grain")
        head = f"  {t.get('name', '?')} — {t.get('description', '')}"
        if grain:
            head += f" [grain: {grain}]"
        lines.append(head)
        for col in t.get("columns", []) or []:
            lines.append(_render_column(col))
    return "\n".join(lines)


def _clean_str(value: Any) -> str:
    return str(value or "").strip()


def _clean_sources(raw: Any) -> list[str]:
    if isinstance(raw, str):
        raw = [raw]
    if not isinstance(raw, list):
        return []
    return [s for s in (_clean_str(x) for x in raw) if s]


def _as_item_list(raw: Any) -> list[Any]:
    """Normalize uncertain top-level containers into a list of candidate items."""
    if isinstance(raw, list):
        return raw
    if isinstance(raw, tuple):
        return list(raw)
    if isinstance(raw, dict):
        return [raw]
    return []


def _clean_region(raw: Any) -> dict[str, Any] | None:
    if not isinstance(raw, dict):
        return None
    rid = _clean_str(raw.get("id"))
    sheet = _clean_str(raw.get("sheet"))
    if not rid or not sheet:
        return None
    region: dict[str, Any] = {"id": rid, "sheet": sheet, "kind": "row_per_entity"}
    data_range = _clean_str(raw.get("data_range"))
    if data_range:
        region["data_range"] = data_range
    row_id = raw.get("row_id")
    if isinstance(row_id, dict):
        cleaned = {}
        for key in ("cell", "header"):
            val = _clean_str(row_id.get(key))
            if val:
                cleaned[key] = val
        if cleaned:
            region["row_id"] = cleaned
    return region


def _clean_field(raw: Any) -> dict[str, Any] | None:
    if not isinstance(raw, dict):
        return None
    region = _clean_str(raw.get("region"))
    cell = _clean_str(raw.get("cell"))
    header = _clean_str(raw.get("header"))
    kind = _clean_str(raw.get("kind")).lower()
    sources = _clean_sources(raw.get("sources"))
    if not (region and cell and header and sources) or kind not in _VALID_KINDS:
        return None
    field: dict[str, Any] = {
        "region": region,
        "cell": cell,
        "header": header,
        "kind": kind,
        "sources": sources,
    }
    how = _clean_str(raw.get("how_to_combine"))
    if how:
        field["how_to_combine"] = how
    code = raw.get("code")
    if isinstance(code, dict) and code:
        field["code"] = {str(k): str(v) for k, v in code.items()}
    return field


def _clean_identity(raw: Any) -> dict[str, Any] | None:
    if not isinstance(raw, dict):
        return None
    anchor = _clean_str(raw.get("anchor"))
    grain = _clean_str(raw.get("grain"))
    rule = _clean_str(raw.get("patient_grain_rule"))
    keys = _clean_sources(raw.get("keys")) or ([anchor] if anchor else [])
    if not (anchor and grain and rule and keys):
        return None
    return {"anchor": anchor, "grain": grain, "keys": keys, "patient_grain_rule": rule}


def _assemble(
    audit_id: str, database_ids: list[str], prose: dict[str, Any]
) -> dict[str, Any]:
    """Coerce the LLM's A2.1-owned portion into the full `mapping.json` shape.

    Injects the deterministic envelope (`schema_version`, `audit`, `databases`) and
    a `criteria_bindings: []` skeleton owned by A6.1 (§3.3)."""
    regions = [
        r for r in (_clean_region(x) for x in _as_item_list(prose.get("regions"))) if r
    ]
    fields = [
        f for f in (_clean_field(x) for x in _as_item_list(prose.get("fields"))) if f
    ]
    # Template-specific per-database one-liners for the library chips (doc 9).
    # Only entries for databases actually bound survive; absent/empty entries
    # simply fall back to the model.json summary in the UI (schema: optional).
    raw_summaries = prose.get("database_summaries")
    database_summaries = {
        db: _clean_str(raw_summaries.get(db))
        for db in database_ids
        if isinstance(raw_summaries, dict) and _clean_str(raw_summaries.get(db))
    }
    model: dict[str, Any] = {
        "schema_version": "1",
        "audit": audit_id,
        "databases": database_ids,
        "description": _clean_str(prose.get("description"))
        or f"Mapping of the {audit_id} audit to {', '.join(database_ids)}.",
        "identity": _clean_identity(prose.get("identity")) or {},
        "regions": regions,
        "fields": fields,
        # Owned by A6.1 (same file); emitted empty so the skeleton is schema-valid.
        "criteria_bindings": [],
        # The audit's FIXED inclusion criteria (mapping.schema.json). Auto-extracted by
        # build_criteria.py; emitted empty here so the skeleton stays schema-valid.
        "fixed_criteria": [],
    }
    if database_summaries:
        model["database_summaries"] = database_summaries
    return model


async def attach_criteria_bindings(
    mapping: dict[str, Any],
    audit: dict[str, Any],
    databases: list[tuple[str, dict[str, Any]]],
) -> dict[str, Any]:
    """Fill the A6.1-owned `criteria_bindings` (+ `not_expressible`) blocks of a
    `mapping.json` document in place and return it.

    A2.1 (this builder) owns the bulk of the document and leaves
    `criteria_bindings: []` as a skeleton; this is the A6.1 contribution to the SAME
    file — one LLM call (`build_criteria_bindings`, reading column types/values by
    reference from `model.json`) selects + binds the audit's inclusion-criteria
    surface, linked to the mapping's `identity` anchor. The `identity` block must
    already be resolved."""
    identity = mapping.get("identity")
    if not isinstance(identity, dict) or not identity:
        raise BuilderValidationError(
            "mapping.identity must be resolved before binding criteria"
        )
    blocks = await build_criteria_bindings(audit, databases, identity=identity)
    mapping["criteria_bindings"] = blocks["criteria_bindings"]
    if blocks.get("not_expressible"):
        mapping["not_expressible"] = blocks["not_expressible"]
    return mapping


async def build_audit_database_mapping(
    audit: dict[str, Any],
    databases: list[tuple[str, dict[str, Any]]],
    *,
    audit_id: str,
) -> dict[str, Any]:
    """Return a validated `mapping.json` document (a dict) binding `audit` to all
    its `databases`.

    `audit` is the audit specification (`spec.json`, a dict). `databases` is a list
    of `(database_id, database_model)` pairs — one per database the audit draws from;
    each `database_model` is that database's `model.json` (a dict). One LLM call
    decides each field's source + `kind` + optional `code` and resolves the cohort
    identity; deterministic code coerces it to the S0 schema, injects the A6.1-owned
    `criteria_bindings: []` skeleton, and validates. Retries on malformed output;
    raises `BuilderValidationError` when the attempts run out."""
    database_ids = [db_id for db_id, _ in databases]
    schema_blocks = "\n\n".join(_render_database_model(model) for _, model in databases)
    user_input = (
        f"audit_id: {audit_id}\n"
        f"databases: {', '.join(database_ids)}\n\n"
        "=== AUDIT SPECIFICATION (spec.json, rendered) ===\n"
        f"{_render_audit_spec(audit)}\n\n"
        f"{schema_blocks}\n"
    )

    async def _attempt(instructions: str) -> tuple[dict[str, Any] | None, list[str]]:
        try:
            prose_typed = await llm.respond_typed(
                instructions,
                user_input,
                _MappingLLMOutput,
                max_tokens=8000,
                temperature=0.0,
                stage="mapping",
            )
            prose = prose_typed.model_dump(mode="python", exclude_none=True)
        except llm.LLMRequestError as exc:
            return None, [str(exc)]
        model = _assemble(audit_id, database_ids, prose)
        problems = validate_against_schema(model, _SCHEMA_FILE)
        if not problems and not model["fields"]:
            problems = ["no usable fields were produced"]
        if not problems:
            # Builder-level requirement (schema keeps the key optional for old
            # documents): a fresh mapping carries one summary per bound db.
            missing = [
                db
                for db in database_ids
                if not (model.get("database_summaries") or {}).get(db)
            ]
            if missing:
                problems = [
                    "database_summaries is missing an entry for: " + ", ".join(missing)
                ]
        if problems:
            return None, problems
        # A6.1 fills the criteria_bindings/not_expressible skeleton via its
        # own (second) LLM call, linking to the identity just resolved.
        model = await attach_criteria_bindings(model, audit, databases)
        # A4 Phase 2: fold the derived executable into the same file
        # (the match is now complete, so the cohort joins resolve). Pure +
        # deterministic — never hand-authored. A compile failure here usually
        # means the match is schema-valid but semantically off (e.g. a source
        # string the schema accepts as text but that isn't "<db> -> t.c"); fold
        # the error into `problems` so the match gets another LLM attempt rather
        # than dying on a fixable mistake.
        try:
            # Thread the measured within-database FK graph + conventions so
            # the compiler can emit multi-hop direct JOINs (Phase C) instead
            # of demoting non-key-table fields to interpret.
            join_graph = {db: m.get("foreign_keys", []) for db, m in databases}
            convs = {db: m.get("conventions", {}) for db, m in databases}
            return fold_executable(model, join_graph=join_graph, conventions=convs), []
        except BuildError as exc:
            return None, [f"the match did not compile into an executable: {exc}"]

    return await build_validated(_attempt, prompt=_PROMPT, label="mapping")


def _read_json(path: Path) -> dict[str, Any] | None:
    if not path.exists():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else None
    except (json.JSONDecodeError, OSError):
        return None


async def ensure_mapping(
    audit_id: str, database_ids: list[str] | str | None
) -> str | None:
    """Return ``mapping_json_text`` for the run orchestrator.

    Reads the audit specification (`spec.json`) and the database model(s)
    (`model.json`) from disk. If a cached `mapping.json` exists next to the
    audit it is returned; otherwise it is built via one LLM call across the
    FULL binding list — one `mapping.json` per audit spans every database it
    draws from (doc 4) — validated, and written. Returns None when required
    inputs aren't available. A single id is accepted for convenience."""
    if isinstance(database_ids, str):
        database_ids = [database_ids]
    if not database_ids:
        return None
    audit = _read_json(TEMPLATES_DIR / audit_id / "spec.json")
    if audit is None:
        return None
    databases: list[tuple[str, dict]] = []
    for database_id in database_ids:
        model = _read_json(DATABASES_DIR / database_id / "model.json")
        if model is None:
            return None
        databases.append((database_id, model))

    mapping_path = TEMPLATES_DIR / audit_id / "mapping.json"
    cached = _read_json(mapping_path)
    if cached is not None:
        return json.dumps(cached, ensure_ascii=False, indent=2)

    try:
        mapping = await build_audit_database_mapping(
            audit, databases, audit_id=audit_id
        )
    except Exception:
        logger.exception(
            "Failed to build mapping for audit %r against databases %r",
            audit_id,
            database_ids,
        )
        return None

    mapping_path.write_text(
        json.dumps(mapping, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    return json.dumps(mapping, ensure_ascii=False, indent=2)
